name: Deploy Documentation

on:
  push:
    tags:
      - '*'
    branches:
      - master
  pull_request:
    branches:
      - master
    types:
      - synchronize

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/doc-setup

      - name: Deploy Documentation for Tagged Versions
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          mike deploy ${GITHUB_REF#refs/tags/} latest --push --update-aliases
          mike set-default latest

      - name: Deploy Documentation for Master
        if: github.ref == 'refs/heads/master'
        run: mike deploy master --push

      - name: Deploy Documentation for Pull Requests
        if: github.event_name == 'pull_request' && github.event.action == 'synchronize'
        run: |
          mike deploy pr-${{ github.event.pull_request.number }}
          mike props pr-${{ github.event.pull_request.number }} --set hidden=true --push
